// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamServer.Data;

#nullable disable

namespace TeamServer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260929184414_AddAdminOperatorCampaigns")]
    partial class AddAdminOperatorCampaigns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trinity.Shared.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Agent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AES256Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Architecure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CampaignID")
                        .HasColumnType("integer");

                    b.Property<string>("CheckInUUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Integrity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Jitter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastCheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.Property<int>("PayloadID")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessPID")
                        .HasColumnType("integer");

                    b.Property<string>("ProcesseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sleep")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CampaignID");

                    b.HasIndex("ListenerID");

                    b.HasIndex("PayloadID");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Campaign", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Trinity.Shared.Models.CampaignBridge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CampaignID")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CampaignID");

                    b.HasIndex("OperatorID");

                    b.ToTable("CampaignBridges");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Header", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Headers");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Listener", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<JsonDocument>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProtocolID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ProtocolID");

                    b.ToTable("Listeners");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Operator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Payload", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Architecture")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.Property<int>("PayloadType")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileID")
                        .HasColumnType("integer");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Payloads");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Protocol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Protocols");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "HTTP"
                        },
                        new
                        {
                            ID = 2,
                            Name = "SMB"
                        },
                        new
                        {
                            ID = 3,
                            Name = "TCP"
                        });
                });

            modelBuilder.Entity("Trinity.Shared.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AgentID")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Command")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CommandType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Trinity.Shared.Models.TaskResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<JsonDocument>("Response")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<bool>("isSuccess")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("TaskID")
                        .IsUnique();

                    b.ToTable("TaskResult");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Agent", b =>
                {
                    b.HasOne("Trinity.Shared.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trinity.Shared.Models.Listener", "Listener")
                        .WithMany()
                        .HasForeignKey("ListenerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trinity.Shared.Models.Payload", "Payload")
                        .WithMany()
                        .HasForeignKey("PayloadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Listener");

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("Trinity.Shared.Models.CampaignBridge", b =>
                {
                    b.HasOne("Trinity.Shared.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trinity.Shared.Models.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trinity.Shared.Models.Listener", b =>
                {
                    b.HasOne("Trinity.Shared.Models.Protocol", "Protocol")
                        .WithMany("Listeners")
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("Trinity.Shared.Models.TaskResult", b =>
                {
                    b.HasOne("Trinity.Shared.Models.Task", null)
                        .WithOne("Result")
                        .HasForeignKey("Trinity.Shared.Models.TaskResult", "TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trinity.Shared.Models.Protocol", b =>
                {
                    b.Navigation("Listeners");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Task", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
