// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamServer.Data;

#nullable disable

namespace TeamServer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trinity.Shared.Models.Agent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CampaignID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Integrity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.Property<int>("PayloadID")
                        .HasColumnType("integer");

                    b.Property<string>("ProcesseName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CampaignID = 1,
                            FirstSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Integrity = 3,
                            LastSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListenerID = 2,
                            PayloadID = 1,
                            ProcesseName = "bitwarden.exe",
                            Status = 1,
                            Type = 1,
                            UUID = "123e4567-e89b-12d3-a456-426655440000",
                            Username = "Lucus"
                        },
                        new
                        {
                            ID = 2,
                            CampaignID = 1,
                            FirstSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Integrity = 2,
                            LastSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListenerID = 2,
                            PayloadID = 1,
                            ProcesseName = "notepad.exe",
                            Status = 1,
                            Type = 1,
                            UUID = "fc32619d-446b-4989-9fcf-2854aae816ac",
                            Username = "mark"
                        },
                        new
                        {
                            ID = 3,
                            CampaignID = 1,
                            FirstSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Integrity = 3,
                            LastSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListenerID = 1,
                            PayloadID = 1,
                            ProcesseName = "explorer.exe",
                            Status = 1,
                            Type = 0,
                            UUID = "123e4567-e89b-12d3-a456-426655440000",
                            Username = "adminEmeris"
                        },
                        new
                        {
                            ID = 4,
                            CampaignID = 1,
                            FirstSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Integrity = 2,
                            LastSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListenerID = 2,
                            PayloadID = 1,
                            ProcesseName = "notepad.exe",
                            Status = 1,
                            Type = 1,
                            UUID = "fc32619d-446b-4989-9fcf-2854aae816ac",
                            Username = "lucus"
                        },
                        new
                        {
                            ID = 5,
                            CampaignID = 2,
                            FirstSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Integrity = 3,
                            LastSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListenerID = 1,
                            PayloadID = 1,
                            ProcesseName = "explorer.exe",
                            Status = 1,
                            Type = 0,
                            UUID = "123e4567-e89b-12d3-a456-426655440000",
                            Username = "admin"
                        },
                        new
                        {
                            ID = 6,
                            CampaignID = 2,
                            FirstSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Integrity = 2,
                            LastSeen = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListenerID = 2,
                            PayloadID = 1,
                            ProcesseName = "notepad.exe",
                            Status = 1,
                            Type = 1,
                            UUID = "fc32619d-446b-4989-9fcf-2854aae816ac",
                            Username = "mark"
                        });
                });

            modelBuilder.Entity("Trinity.Shared.Models.Campaign", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Emeris Campaign",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            Name = "Robocorp Campaign",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Trinity.Shared.Models.Header", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Headers");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Listener", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Listeners", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "HTTP Listener",
                            Type = 2
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TCP Listener",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Trinity.Shared.Models.ListenerBase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ListenerID")
                        .IsUnique();

                    b.ToTable("ListenerBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Trinity.Shared.Models.ListenerHost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HttpListenerID")
                        .HasColumnType("integer");

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("HttpListenerID");

                    b.ToTable("ListenerHosts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Host = "www.test.com",
                            ListenerID = 1
                        },
                        new
                        {
                            ID = 2,
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Host = "www.hello.com",
                            ListenerID = 1
                        });
                });

            modelBuilder.Entity("Trinity.Shared.Models.Payload", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Architecture")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListenerID")
                        .HasColumnType("integer");

                    b.Property<int>("PayloadType")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileID")
                        .HasColumnType("integer");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Payloads");
                });

            modelBuilder.Entity("Trinity.Shared.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AgentID")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Command")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CommandType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Trinity.Shared.Models.TaskResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<JsonDocument>("Response")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<bool>("isSuccess")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("TaskID")
                        .IsUnique();

                    b.ToTable("TaskResult");
                });

            modelBuilder.Entity("Trinity.Shared.Models.HttpListener", b =>
                {
                    b.HasBaseType("Trinity.Shared.Models.ListenerBase");

                    b.Property<int>("BindPort")
                        .HasColumnType("integer");

                    b.Property<int>("C2Port")
                        .HasColumnType("integer");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<int>("HostRotationStrategy")
                        .HasColumnType("integer");

                    b.Property<string>("MaxRetryStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.ToTable("HttpListeners", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ListenerID = 1,
                            Name = "HTTP Listener",
                            BindPort = 8888,
                            C2Port = 8888,
                            Header = "X-Agent",
                            HostRotationStrategy = 0,
                            MaxRetryStrategy = "HHH/MMM/SSSS",
                            UserAgent = "User Agent"
                        });
                });

            modelBuilder.Entity("Trinity.Shared.Models.TcpListener", b =>
                {
                    b.HasBaseType("Trinity.Shared.Models.ListenerBase");

                    b.Property<bool>("LocalHostOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.ToTable("TcpListeners", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 2,
                            ListenerID = 2,
                            Name = "TCP Listener",
                            LocalHostOnly = true,
                            Port = 2000
                        });
                });

            modelBuilder.Entity("Trinity.Shared.Models.ListenerBase", b =>
                {
                    b.HasOne("Trinity.Shared.Models.Listener", "Listener")
                        .WithOne("Listeners")
                        .HasForeignKey("Trinity.Shared.Models.ListenerBase", "ListenerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listener");
                });

            modelBuilder.Entity("Trinity.Shared.Models.ListenerHost", b =>
                {
                    b.HasOne("Trinity.Shared.Models.HttpListener", null)
                        .WithMany("Hosts")
                        .HasForeignKey("HttpListenerID");
                });

            modelBuilder.Entity("Trinity.Shared.Models.TaskResult", b =>
                {
                    b.HasOne("Trinity.Shared.Models.Task", null)
                        .WithOne("Result")
                        .HasForeignKey("Trinity.Shared.Models.TaskResult", "TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trinity.Shared.Models.HttpListener", b =>
                {
                    b.HasOne("Trinity.Shared.Models.ListenerBase", null)
                        .WithOne()
                        .HasForeignKey("Trinity.Shared.Models.HttpListener", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trinity.Shared.Models.TcpListener", b =>
                {
                    b.HasOne("Trinity.Shared.Models.ListenerBase", null)
                        .WithOne()
                        .HasForeignKey("Trinity.Shared.Models.TcpListener", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trinity.Shared.Models.Listener", b =>
                {
                    b.Navigation("Listeners")
                        .IsRequired();
                });

            modelBuilder.Entity("Trinity.Shared.Models.Task", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Trinity.Shared.Models.HttpListener", b =>
                {
                    b.Navigation("Hosts");
                });
#pragma warning restore 612, 618
        }
    }
}
